[package]
name = "devkit-ext-database"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Database operations for devkit"

[dependencies]
anyhow.workspace = true
devkit-core.workspace = true
