[package]
name = "devkit-ext-k8s"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Kubernetes operations extension for devkit"

[dependencies]
anyhow.workspace = true
devkit-core.workspace = true
